id = "cobalt2"
name = "Cobalt2"
version = "0.1.0"
schema_version = 1
authors = ["MD. MOHIBUR RAHMAN <mrpmohiburrahman@gmail.com>"]
description = "Cobalt2 theme for Zed"
repository = "https://github.com/mrpmohiburrahman/cobalt2-zed"
